// <auto-generated />
using System;
using CodeFirstTask.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirstTask.Migrations
{
    [DbContext(typeof(AppDbcontext))]
    partial class AppDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("CodeFirstTask.Entitys.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "HR"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "IT"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "Finance"
                        },
                        new
                        {
                            DepartmentId = 4,
                            DepartmentName = "Marketing"
                        },
                        new
                        {
                            DepartmentId = 5,
                            DepartmentName = "Sales"
                        });
                });

            modelBuilder.Entity("CodeFirstTask.Entitys.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            DepartmentId = 1,
                            FullName = "Ahmed Ali"
                        },
                        new
                        {
                            EmployeeId = 2,
                            DepartmentId = 2,
                            FullName = "Sara Mohamed"
                        },
                        new
                        {
                            EmployeeId = 3,
                            DepartmentId = 3,
                            FullName = "Omar Hassan"
                        },
                        new
                        {
                            EmployeeId = 4,
                            DepartmentId = 4,
                            FullName = "Mona Ibrahim"
                        },
                        new
                        {
                            EmployeeId = 5,
                            DepartmentId = 5,
                            FullName = "Khaled Mahmoud"
                        });
                });

            modelBuilder.Entity("CodeFirstTask.Entitys.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            ProjectName = "ERP System",
                            StartDate = new DateTime(2025, 8, 18, 0, 2, 45, 107, DateTimeKind.Local).AddTicks(5849)
                        },
                        new
                        {
                            ProjectId = 2,
                            ProjectName = "Website Redesign",
                            StartDate = new DateTime(2025, 8, 18, 0, 2, 45, 107, DateTimeKind.Local).AddTicks(5893)
                        },
                        new
                        {
                            ProjectId = 3,
                            ProjectName = "Mobile App",
                            StartDate = new DateTime(2025, 8, 18, 0, 2, 45, 107, DateTimeKind.Local).AddTicks(5896)
                        },
                        new
                        {
                            ProjectId = 4,
                            ProjectName = "CRM Integration",
                            StartDate = new DateTime(2025, 8, 18, 0, 2, 45, 107, DateTimeKind.Local).AddTicks(5912)
                        },
                        new
                        {
                            ProjectId = 5,
                            ProjectName = "AI Chatbot",
                            StartDate = new DateTime(2025, 8, 18, 0, 2, 45, 107, DateTimeKind.Local).AddTicks(5915)
                        });
                });

            modelBuilder.Entity("EmployeeProject", b =>
                {
                    b.Property<int>("EmployessEmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectsProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmployessEmployeeId", "ProjectsProjectId");

                    b.HasIndex("ProjectsProjectId");

                    b.ToTable("EmployeeProjects", (string)null);
                });

            modelBuilder.Entity("CodeFirstTask.Entitys.Employee", b =>
                {
                    b.HasOne("CodeFirstTask.Entitys.Department", "Department")
                        .WithMany("Employess")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EmployeeProject", b =>
                {
                    b.HasOne("CodeFirstTask.Entitys.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployessEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirstTask.Entitys.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CodeFirstTask.Entitys.Department", b =>
                {
                    b.Navigation("Employess");
                });
#pragma warning restore 612, 618
        }
    }
}
